"""
agent/tools/sql_validator.py
------------------------------
Safety gate between LLM-generated SQL and the Supabase database.
Every SQL query from the intent router must pass validation before execution.

Called exclusively by tools/db_tools.py before any query is executed.

Checks:
  1. Keyword blacklist  — blocks destructive or unauthorized operations
  2. Table whitelist    — only approved patient-facing tables allowed
  3. patient_id filter  — every query must filter by patient_id
  4. Single statement   — no stacked queries allowed

Returns:
  (True, None)          → query is safe to execute
  (False, reason: str)  → query is blocked, reason logged
"""

import logging
import re

logger = logging.getLogger(__name__)


# Only SELECT is permitted — agent never modifies data directly
BLACKLISTED_KEYWORDS = {
    "DROP", "DELETE", "UPDATE", "INSERT", "ALTER",
    "TRUNCATE", "CREATE", "EXEC", "EXECUTE", "GRANT",
    "REVOKE", "REPLACE", "MERGE", "CALL", "EXPLAIN"
}

# Only patient-facing tables are queryable
# Internal system tables are explicitly excluded:
# interaction_log, short_term_memory, long_term_memory
ALLOWED_TABLES = {
    "patients",
    "caregiver",
    "family_member",
    "medication",
    "patient_medications",
    "patient_meals",
    "patient_activities",
    "reminders",
    "meals",
    "activity",
    "alerts",
    "report",
    "caregiver_priority"
}


def validate_sql(sql: str, patient_id: int) -> tuple[bool, str | None]:
    """
    Validates an LLM-generated SQL query before execution.

    Args:
        sql:        The raw SQL string generated by the intent router.
        patient_id: The active patient's ID — must appear in the query.

    Returns:
        (True, None)         if the query passes all checks.
        (False, reason)      if the query is blocked — reason is logged.
    """

    if not sql or not sql.strip():
        reason = "SQL query is empty."
        logger.error(f"[SQL VALIDATOR] Blocked — {reason}")
        return False, reason


    # Normalize for keyword checking — uppercase, strip extra whitespace
    sql_upper = sql.upper().strip()


    # ── Check 1: Single statement only ──────────────────────────────────────
    # Strip trailing semicolon then check for any remaining semicolon
    sql_stripped = sql_upper.rstrip(";")
    if ";" in sql_stripped:
        reason = "Multiple SQL statements detected — only one statement allowed."
        logger.error(f"[SQL VALIDATOR] Blocked — {reason} | SQL: {sql}")
        return False, reason


    # ── Check 2: Must start with SELECT ─────────────────────────────────────
    if not sql_upper.lstrip().startswith("SELECT"):
        reason = "Only SELECT statements are permitted."
        logger.error(f"[SQL VALIDATOR] Blocked — {reason} | SQL: {sql}")
        return False, reason


    # ── Check 3: Keyword blacklist ───────────────────────────────────────────
    # Tokenize to avoid partial matches (e.g. "CREATED_AT" triggering "CREATE")
    tokens = set(re.findall(r"\b[A-Z_]+\b", sql_upper))
    found_blacklisted = tokens & BLACKLISTED_KEYWORDS
    if found_blacklisted:
        reason = f"Blacklisted keyword(s) detected: {found_blacklisted}"
        logger.error(f"[SQL VALIDATOR] Blocked — {reason} | SQL: {sql}")
        return False, reason


    # ── Check 4: Table whitelist ─────────────────────────────────────────────
    # Extract all table names referenced after FROM and JOIN keywords
    table_pattern = re.findall(
        r"\b(?:FROM|JOIN)\s+([a-zA-Z_][a-zA-Z0-9_]*)",
        sql,
        re.IGNORECASE
    )
    referenced_tables = {t.lower() for t in table_pattern}
    disallowed_tables = referenced_tables - ALLOWED_TABLES
    if disallowed_tables:
        reason = f"Query references unauthorized table(s): {disallowed_tables}"
        logger.error(f"[SQL VALIDATOR] Blocked — {reason} | SQL: {sql}")
        return False, reason


    # ── Check 5: patient_id filter ───────────────────────────────────────────
    # Every query must contain a patient_id = filter to prevent cross-patient leaks
    patient_id_pattern = re.search(
        rf"patient_id\s*=\s*{patient_id}",
        sql,
        re.IGNORECASE
    )
    if not patient_id_pattern:
        reason = f"Query missing required WHERE patient_id = {patient_id} filter."
        logger.error(f"[SQL VALIDATOR] Blocked — {reason} | SQL: {sql}")
        return False, reason


    # ── All checks passed ────────────────────────────────────────────────────
    logger.info(f"[SQL VALIDATOR] Passed — patient_id={patient_id} | SQL: {sql}")
    return True, None