# -*- coding: utf-8 -*-
"""embedding_bge_openAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c_OrehGcaOd-vCknwgoF7X5Shi92Tx8Y
"""

#pip install -q openai chromadb tqdm

import os
os.environ["OPENAI_API_KEY"] = ""

'''from google.colab import drive
drive.mount('/content/drive')'''

from openai import OpenAI
import os

client_oai = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

import json
from tqdm import tqdm
import chromadb
from sentence_transformers import SentenceTransformer

# ── CONFIG ─────────────────────────────────────────────
CHUNKS_FILE = "/content/drive/MyDrive/all_medicine_chunks.json"
CHROMA_PATH = "/content/chroma_db"

BATCH_SIZE_BGE = 256
BATCH_SIZE_OAI = 128

# ── LOAD DATA ──────────────────────────────────────────
with open(CHUNKS_FILE, "r", encoding="utf-8") as f:
    chunks = json.load(f)

print(f"Loaded {len(chunks)} chunks")

# ── MODELS ─────────────────────────────────────────────
print("Loading BGE-M3...")
bge_model = SentenceTransformer("BAAI/bge-m3", device="cuda")

print("Using OpenAI embeddings...")

# ── CHROMA (ONE DB) ────────────────────────────────────
client = chromadb.PersistentClient(path=CHROMA_PATH)

# 🔥 Create BOTH collections
bge_collection = client.get_or_create_collection("medicines_bge")
oai_collection = client.get_or_create_collection("medicines_openai")

# ──────────────────────────────────────────────────────
# 🔵 BGE INDEXING
# ──────────────────────────────────────────────────────
print("\n🔵 Indexing BGE...")

all_ids, all_docs, all_meta, all_embeds = [], [], [], []

for i in tqdm(range(0, len(chunks), BATCH_SIZE_BGE), desc="BGE"):
    batch = chunks[i:i+BATCH_SIZE_BGE]
    texts = [c["text"] for c in batch]

    embeddings = bge_model.encode(
        texts,
        prompt="Represent this sentence for searching relevant passages: ",
        batch_size=BATCH_SIZE_BGE,
        normalize_embeddings=True,
        convert_to_numpy=True,
        show_progress_bar=False
    )

    for j, chunk in enumerate(batch):
        meta = chunk.get("metadata", {})

        all_ids.append(chunk["chunk_id"])
        all_docs.append(texts[j])
        all_meta.append({
            "generic_name": meta.get("generic_name", "").lower(),
            "chunk_type": meta.get("chunk_type", "").lower(),
            "brand_names": meta.get("brand_names", "").lower()
        })
        all_embeds.append(embeddings[j])

bge_collection.add(
    documents=all_docs,
    embeddings=all_embeds,
    metadatas=all_meta,
    ids=all_ids
)

print("✅ BGE done")


# 🟣 OPENAI INDEXING

print("\n🟣 Indexing OpenAI...")

def embed_openai_batch(texts):
    response = client_oai.embeddings.create(
        input=texts,
        model="text-embedding-3-large"
    )
    return [r.embedding for r in response.data]

all_ids, all_docs, all_meta, all_embeds = [], [], [], []

for i in tqdm(range(0, len(chunks), BATCH_SIZE_OAI), desc="OpenAI"):
    batch = chunks[i:i+BATCH_SIZE_OAI]
    texts = [c["text"] for c in batch]

    embeddings = embed_openai_batch(texts)

    for j, chunk in enumerate(batch):
        meta = chunk.get("metadata", {})

        all_ids.append(chunk["chunk_id"])
        all_docs.append(texts[j])
        all_meta.append({
            "generic_name": meta.get("generic_name", "").lower(),
            "chunk_type": meta.get("chunk_type", "").lower(),
            "brand_names": meta.get("brand_names", "").lower()
        })
        all_embeds.append(embeddings[j])

oai_collection.add(
    documents=all_docs,
    embeddings=all_embeds,
    metadatas=all_meta,
    ids=all_ids
)

print("✅ OpenAI done")

# ── VERIFY ─────────────────────────────────────────────
print("\n📦 Collections inside DB:")
for col in client.list_collections():
    print("-", col.name)

#!cp -r /content/chroma_db /content/drive/MyDrive/chroma_db
print("Saved BOTH collections to Drive")